// <auto-generated />
using System;
using AmgSistemas.ControleMilhas.Api.BD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AmgSistemas.ControleMilhas.Api.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20211030130138_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TCOTACAO", b =>
                {
                    b.Property<string>("ID_COTACAO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DTH_COTACAO")
                        .HasColumnType("datetime2");

                    b.Property<string>("ID_EMPRESA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_PROGRAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NUM_VALOR")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_COTACAO");

                    b.HasIndex("ID_EMPRESA");

                    b.HasIndex("ID_PROGRAMA");

                    b.ToTable("AGCM_TCOTACAO");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TEMPRESA", b =>
                {
                    b.Property<string>("ID_EMPRESA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DES_EMPRESA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_EMPRESA");

                    b.ToTable("AGCM_TEMPRESA");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TMOVIMENTOS", b =>
                {
                    b.Property<string>("ID_MOVIMENTOS")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("COD_TIPO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_MOVIMENTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DTH_MOVIMENTO")
                        .HasColumnType("datetime2");

                    b.Property<string>("ID_PROGRAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_USUARIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NUM_VALOR_TOTAL_GASTO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QTD_PARCELAS")
                        .HasColumnType("int");

                    b.HasKey("ID_MOVIMENTOS");

                    b.HasIndex("ID_PROGRAMA");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("AGCM_TMOVIMENTOS");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TMOV_PARCELA", b =>
                {
                    b.Property<string>("ID_MOV_PARCELA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("BOL_MILHAS_RECEBIDAS")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DTH_PAGAMENTO")
                        .HasColumnType("datetime2");

                    b.Property<string>("ID_MOVIMENTOS")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NUM_MILHAS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NUM_VALOR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NUM_VALOR_MILHEIRO")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_MOV_PARCELA");

                    b.HasIndex("ID_MOVIMENTOS");

                    b.ToTable("AGCM_TMOV_PARCELA");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TPROGRAMA", b =>
                {
                    b.Property<string>("ID_PROGRAMA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DES_PROGRAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PROGRAMA");

                    b.ToTable("AGCM_TPROGRAMA");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TSALDO", b =>
                {
                    b.Property<string>("ID_SALDO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DTH_MODIFICACAO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DTH_REGISTRO")
                        .HasColumnType("datetime2");

                    b.Property<string>("ID_PROGRAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_USUARIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NUM_MILHAS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NUM_MILHAS_VENDIDAS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NUM_VALOR_COMPRA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_SALDO");

                    b.HasIndex("ID_PROGRAMA");

                    b.HasIndex("ID_USUARIO");

                    b.ToTable("AGCM_TSALDO");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TSALDO_VENDA", b =>
                {
                    b.Property<string>("ID_SALDO_VENDA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DTH_REGISTRO")
                        .HasColumnType("datetime2");

                    b.Property<string>("ID_EMPRESA")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_SALDO")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NUM_MILHAS_VENDIDAS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NUM_VALOR_MILHEIRO")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_SALDO_VENDA");

                    b.HasIndex("ID_EMPRESA");

                    b.HasIndex("ID_SALDO");

                    b.ToTable("AGCM_TSALDO_VENDA");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TUSUARIO", b =>
                {
                    b.Property<string>("ID_USUARIO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DES_LOGIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_NOME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES_SENHA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DTH_REGISTRO")
                        .HasColumnType("datetime2");

                    b.HasKey("ID_USUARIO");

                    b.ToTable("AGCM_TUSUARIO");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TCOTACAO", b =>
                {
                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TEMPRESA", "AGCM_EMPRESA")
                        .WithMany("AGCM_TCOTACAO")
                        .HasForeignKey("ID_EMPRESA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TPROGRAMA", "AGCM_TPROGRAMA")
                        .WithMany("AGCM_TCOTACAO")
                        .HasForeignKey("ID_PROGRAMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AGCM_EMPRESA");

                    b.Navigation("AGCM_TPROGRAMA");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TMOVIMENTOS", b =>
                {
                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TPROGRAMA", "AGCM_TPROGRAMA")
                        .WithMany("AGCM_TMOVIMENTOS")
                        .HasForeignKey("ID_PROGRAMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TUSUARIO", "AGCM_TUSUARIO")
                        .WithMany("AGCM_TMOVIMENTOS")
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AGCM_TPROGRAMA");

                    b.Navigation("AGCM_TUSUARIO");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TMOV_PARCELA", b =>
                {
                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TMOVIMENTOS", "AGCM_TMOVIMENTOS")
                        .WithMany("AGCM_TMOV_PARCELA")
                        .HasForeignKey("ID_MOVIMENTOS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AGCM_TMOVIMENTOS");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TSALDO", b =>
                {
                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TPROGRAMA", "AGCM_TPROGRAMA")
                        .WithMany("AGCM_TSALDO")
                        .HasForeignKey("ID_PROGRAMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TUSUARIO", "AGCM_TUSUARIO")
                        .WithMany("AGCM_TSALDO")
                        .HasForeignKey("ID_USUARIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AGCM_TPROGRAMA");

                    b.Navigation("AGCM_TUSUARIO");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TSALDO_VENDA", b =>
                {
                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TEMPRESA", "AGCM_TEMPRESA")
                        .WithMany("AGCM_TSALDO_VENDA")
                        .HasForeignKey("ID_EMPRESA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TSALDO", "AGCM_TSALDO")
                        .WithMany("AGCM_TSALDO_VENDA")
                        .HasForeignKey("ID_SALDO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AGCM_TEMPRESA");

                    b.Navigation("AGCM_TSALDO");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TEMPRESA", b =>
                {
                    b.Navigation("AGCM_TCOTACAO");

                    b.Navigation("AGCM_TSALDO_VENDA");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TMOVIMENTOS", b =>
                {
                    b.Navigation("AGCM_TMOV_PARCELA");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TPROGRAMA", b =>
                {
                    b.Navigation("AGCM_TCOTACAO");

                    b.Navigation("AGCM_TMOVIMENTOS");

                    b.Navigation("AGCM_TSALDO");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TSALDO", b =>
                {
                    b.Navigation("AGCM_TSALDO_VENDA");
                });

            modelBuilder.Entity("AmgSistemas.ControleMilhas.Api.BD.Models.AGCM_TUSUARIO", b =>
                {
                    b.Navigation("AGCM_TMOVIMENTOS");

                    b.Navigation("AGCM_TSALDO");
                });
#pragma warning restore 612, 618
        }
    }
}
